kind: Deployment
apiVersion: apps/v1
metadata:
   name: nfs-provisioner
   labels:
     app: nfs
   namespace: monitor
spec:
   replicas: 1
   strategy:
     type: Recreate
   selector:
     matchLabels:
       app: nfs
   template:
      metadata:
         labels:
            app: nfs
      spec:
         serviceAccount: nfs-provisioner
         containers:
            -  name: nfs-provisioner
               image: quay.io/external_storage/nfs-client-provisioner:latest
               volumeMounts:
                 -  name: nfs-root
                    mountPath: /persistentvolumes
               env:
                 -  name: PROVISIONER_NAME
                    value: fuseim.pri/ifs
                 -  name: NFS_SERVER
                    value: 10.0.0.18
                 -  name: NFS_PATH
                    value: /data/nfs
         volumes:
           - name: nfs-root
             nfs:
               server: 10.0.0.18
               path: /data/nfs