apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-database
  namespace: devops
  labels:
    k8s-app: sonarqube-database
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-database
  labels:
    k8s-app: sonarqube-database
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: sonarqube-database
  labels:
    k8s-app: sonarqube-database
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: sonarqube-database
    namespace: devops
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: sonarqube-database
  apiGroup: ""

