apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-nexus
  namespace: devops
subsets:
- addresses:
  - ip: 10.235.9.42
  - ip: 10.235.9.43
  - ip: 10.235.9.44
  ports:
  - port: 49160
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-nexus
  namespace: devops
spec:
  ports:
    - port: 49160
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-glusterfs-pv
  namespace: devops
  labels:
    pv: nexus
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-nexus
    path: nexus
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-glusterfs-pvc
  namespace: devops
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      pv: "nexus"
