apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-database-pv
  namespace: devops
  labels:
    pv: keycloak-database-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany   
  nfs:
    path: /data/keycloak/keycloak-database
    server: 10.0.0.18
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-database-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      pv: "keycloak-database-pv"
