FROM centos:7
MAINTAINER linuxwt <tengwanginit@gmail.com>

######配置jdk#####
WORKDIR /usr
RUN mkdir /usr/local/java
ADD jdk-8u202-linux-x64.tar.gz /usr/local/java
RUN ln -s /usr/local/java/jdk1.8.0_202 /usr/local/java/jdk 
ENV JAVA_HOME /usr/local/java/jdk 
ENV JRE_HOME ${JAVA_HOME}/jre 
ENV CLASSPATH .:${JAVA_HOME}/lib:${JRE_HOME}/lib 
ENV PATH ${JAVA_HOME}/bin:$PATH 