apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: v1.21.1
dns: 
  type: CoreDNS
networking: 
  serviceSubnet: "10.96.0.0/16" 
  podSubnet: "10.244.0.0/16" 
  dnsDomain: "cluster.local"
