kind: ConfigMap
apiVersion: v1
metadata:
  name: beat-config
data:
  filebeat.yml: |-
    #=========================== Filebeat inputs =============================
    filebeat.inputs:
    # 收集nginx日志
    - type: log
      enabled: true
      paths:
        - /usr/local/nginx/logs/access.log
    # 日志是json开启这个
      json.keys_under_root: true
      json.overwrite_keys: true
      json.add_error_key: true

    #-------------------------- Redis output ------------------------------
    output.redis:
      hosts: ["redis.monitor:6379"]   #输出到redis的机器
      password: "Qazwsx!23"
      key: "nginx_logs"   #redis中日志数据的key值? 
      db: 0
      timeout: 5

  nginx.conf: |-   
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format aka_logs
            '{"@timestamp":"$time_iso8601",'
            '"host":"$hostname",'
            '"server_ip":"$server_addr",'
            '"client_ip":"$remote_addr",'
            '"xff":"$http_x_forwarded_for",'
            '"domain":"$host",'
            '"url":"$uri",'
            '"referer":"$http_referer",'
            '"args":"$args",'
            '"upstreamtime":"$upstream_response_time",'
            '"responsetime":"$request_time",'
            '"request_method":"$request_method",'
            '"status":"$status",'
            '"size":"$body_bytes_sent",'
            '"request_body":"$request_body",'
            '"request_length":"$request_length",'
            '"protocol":"$server_protocol",'
            '"upstreamhost":"$upstream_addr",'
            '"file_dir":"$request_filename",'
            '"http_user_agent":"$http_user_agent"'
            '}';
        access_log  /var/log/nginx/access.log  aka_logs;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
        }