apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-proxy
  namespace: monitor
  labels:
    k8s-app: keycloak-proxy
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-proxy
  labels:
    k8s-app: keycloak-proxy
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitor
  name: keycloak-proxy
  labels:
    k8s-app: keycloak-proxy
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: keycloak-proxy
    namespace: monitor
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: keycloak-proxy
  apiGroup: ""

