apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: front
#  namespace: apptest
spec: 
  selector:
    matchLabels:
      name: front
  template: 
    metadata: 
      labels: 
        name: front
    spec: 
      containers: 
        - name: front
          image: front:1.0.5
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8090
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 200Mi
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      nodeSelector:
        kubernetes.io/hostname: node10
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
kind: Service
apiVersion: v1
metadata:
  name: front-svc
 # namespace: apptest
  labels:
    name: front
  annotations:
    description: Exposes Front  Service
spec:
  #type: ClusterIP
  type: NodePort
  selector:     
    name: front    
  ports:
    - name: front
      port: 8090
      targetPort: 8090
      nodePort: 30103
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  #namespace: apptest
spec:
  redirectScheme:
    scheme: https
    port: "443"
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: front-http-route
  #namespace: apptest
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`front.k8s`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: front-svc
          port: 8090
#      middlewares:
#        - name: redirect-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: front-https-route
  #namespace: apptest
spec:
  entryPoints:
    - websecure
  tls:
    secretName: front.k8s-tls
  routes:
    - match: Host(`front.k8s`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: front-svc
          port: 8090
