apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-test-default
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: "test"
