apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: default
  labels:
    app: test
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-test-default"
    path: "test"
    readOnly: false
