apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-conf
  namespace: devops
  labels:
    app: sonarqube
    component: conf
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.18
    path: /data/sonarqube/conf
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data
  namespace: devops
  labels:
    app: sonarqube
    component: data
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.18
    path: /data/sonarqube/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions
  namespace: devops
  labels:
    app: sonarqube
    component: extensions
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.18
    path: /data/sonarqube/extensions

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-conf
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "sonarqube"
      component: "conf"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "sonarqube"
      component: "data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extensions
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "sonarqube"
      component: "extensions"

