apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-gitlab
  namespace: devops
subsets:
- addresses:
  - ip: 10.235.9.42
  - ip: 10.235.9.43
  - ip: 10.235.9.44
  ports:
  - port: 49157
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-gitlab
  namespace: devops
spec:
  ports:
    - port: 49157
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-glusterfs-pv
  namespace: devops
  labels:
    pv: gitlab
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-gitlab
    path: gitlab
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-glusterfs-pvc
  namespace: devops
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv: "gitlab"
