apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: logstash
  namespace: monitor
spec: 
  selector:
    matchLabels:
      name: logstash
  template: 
    metadata: 
      labels: 
        name: logstash
    spec: 
      serviceAccountName: logstash
      containers: 
        - name: logstash 
          image: logstash:7.9.1-TZ
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: logstash-config
              mountPath: "/usr/share/logstash/pipeline/logstash.conf"
              subPath: logstash.conf
            - name: logstash-xpack
              mountPath: "/usr/share/logstash/config/logstash.yml"
              subPath: logstash.yml
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
      - name: logstash-xpack
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai         
      nodeSelector:
        app: monitor