apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitor
  labels:
    app: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.18
    path: /data/grafana
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "grafana"