name: Build
on:
  pull_request:
    # paths-ignore means we run the action when files have changed and no one them are Golang files.
    paths-ignore:
    - '**.go'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: build rook
      run: |
        # set VERSION to a dummy value since Jenkins normally sets it for us. Do this to make Helm happy and not fail with "Error: Invalid Semantic Version"
        GOPATH=$(go env GOPATH) make clean && make -j$nproc IMAGES='ceph' VERSION=0 build
