name: MacOS build
on:
  pull_request:

jobs:
  macos-build:
    runs-on: macos-10.15
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: copy working directory to GOPATH
      run: sudo mkdir -p /Users/runner/go/src/github.com && sudo cp -a /Users/runner/work/rook /Users/runner/go/src/github.com/

    - name: build rook
      working-directory: /Users/runner/go/src/github.com/rook/rook
      run: |
        # set VERSION to a dummy value since Jenkins normally sets it for us. Do this to make Helm happy and not fail with "Error: Invalid Semantic Version"
        GOPATH=$(go env GOPATH) make clean && make -j$nproc IMAGES='ceph' VERSION=0 BUILD_CONTAINER_IMAGE=false build

    - name: run codegen
      working-directory: /Users/runner/go/src/github.com/rook/rook
      run: GOPATH=$(go env GOPATH) make codegen

    - name: validate codegen
      working-directory: /Users/runner/go/src/github.com/rook/rook
      run: tests/scripts/validate_modified_files.sh codegen

    - name: run mod check
      run: GOPATH=$(go env GOPATH) make -j $(nproc) mod.check

    - name: validate modcheck
      run: tests/scripts/validate_modified_files.sh modcheck

    - name: run crds-gen
      working-directory: /Users/runner/go/src/github.com/rook/rook
      run: make csv-clean && GOPATH=$(go env GOPATH) make crds

    - name: validate crds-gen
      working-directory: /Users/runner/go/src/github.com/rook/rook
      run: tests/scripts/validate_modified_files.sh crd

    - name: setup tmate session for debugging
      if: failure()
      uses: mxschmitt/action-tmate@v3
