name: Unit tests
on:
  pull_request:
    paths:
    - '**.go'
    - build/makelib/golang.mk
    - Makefile

jobs:
  unittests:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: copy working directory to GOPATH
      run: sudo mkdir -p /home/runner/go/src/github.com && sudo cp -a /home/runner/work/rook /home/runner/go/src/github.com/

    - name: run unit tests
      working-directory: /home/runner/go/src/github.com/rook/rook
      run: GOPATH=$(go env GOPATH) make -j $(nproc) test

