apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nacos
  namespace: devops
spec: 
  selector:
    matchLabels:
      name: nacos
  template: 
    metadata: 
      labels: 
        name: nacos
    spec: 
      containers: 
        - name: nacos 
          image: nacos/nacos-server:latest
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8848
              name: http-nacos
              protocol: TCP
          env:
            - name: MODE
              value: standalone
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      nodeSelector:
        app: devops
---
kind: Service
apiVersion: v1
metadata:
  name: nacos-svc
  namespace: devops
  labels:
    name: nacos
  annotations:
    description: Exposes Nacos Service
spec:
  type: NodePort
  selector:     
    name: nacos    
  ports:
    - name: nacos
      port: 8848
      targetPort: 8848
      nodePort: 30102
