apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: devops
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4wLjAuMTk6MzAwMDIiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2VVdGNmQzTjRJVEl6IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy45IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
