apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-glusterfs
spec: 
  replicas: 2
  selector:
    matchLabels:
      name: nginx-glusterfs
  template: 
    metadata: 
      labels: 
        name: nginx-glusterfs
    spec: 
      containers: 
        - name: nginx 
          image: nginx 
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 80
          volumeMounts:
            - name: nginx-dev-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nginx-dev-volume
        persistentVolumeClaim:
          claimName: glusterfs-nginx
