apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitor
  labels:
    name: elasticsearch
spec:
  type: NodePort
  ports:
  - name:  web-9200
    port: 9200
    targetPort: 9200
    protocol: TCP
    nodePort: 30001
  selector:
    name: elasticsearch