apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nexus
  namespace: devops
spec: 
  selector:
    matchLabels:
      name: nexus
  template: 
    metadata: 
      labels: 
        name: nexus
    spec: 
      serviceAccountName: nexus
      containers: 
        - name: nexus 
          image: sonatype/nexus3
          imagePullPolicy: IfNotPresent
          env:
            - name: NEXUS_CONTEXT
              value: nexus
          ports: 
            - containerPort: 8081
            - containerPort: 8082
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: nexus
              mountPath: "/nexus-data"
      volumes:
      - name: nexus
        persistentVolumeClaim:
          claimName: nexus-pvc
      nodeSelector:
        app: devops
