apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: kibana
  namespace: monitor
spec: 
  selector:
    matchLabels:
      name: kibana
  template: 
    metadata: 
      labels: 
        name: kibana
    spec: 
      serviceAccountName: kibana
      containers: 
        - name: kibana 
          image: kibana:7.9.1
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 5601
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: kibana-config
              mountPath: "/usr/share/kibana/config"
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-configmap
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai         
      nodeSelector:
        app: monitor