apiVersion: v1
kind: Service
metadata:
  name: sonarqube-database
  namespace: devops
  labels:
    app: sonarqube-database
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: sonarqube-database

