apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-nginx
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-dev-volume
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "revolume"
    readOnly: false
